#!/usr/bin/env python
# -*- coding: utf-8 -*- 
#Refrescador automatico de clines
#Creado por Dagger - https://github.com/gavazquez

#If version is 0 or less it will mean that we will delete that file

Versions = {
    "ReloadCam_Arguments" : 29,
    "ReloadCam_ClineTester" : 5,
    "ReloadCam_Helper" : 23,
    "ReloadCam_NlineTester" : 7,
    "ReloadCam_Main" : 33,
    "ReloadCam_Importlib" : 1,
    "ReloadCam_Server_Allcam" : 10,
    "ReloadCam_Server_Cccam4you" : 0,
    "ReloadCam_Server_Cccamcafard" : 0,
    "ReloadCam_Server_Cccamfree" : 4,
    "ReloadCam_Server_Cccamgenerator" : 7,
    "ReloadCam_Server_Cccamgratis" : 0,
    "ReloadCam_Server_Elaissaoui" : 0,
    "ReloadCam_Server_Freecline" : 10,
    "ReloadCam_Server_Fullmonsters" : 0,
    "ReloadCam_Server_Greencccamfree" : 0,
    "ReloadCam_Server_Hacksat" : 0,
    "ReloadCam_Server_Jokercccam" : 0,
    "ReloadCam_Server_Kacsat" : 0,
    "ReloadCam_Server_Mycccam" : 1,
    "ReloadCam_Server_Realtv1" : 0,
    "ReloadCam_Server_Raul7" : 0,
    "ReloadCam_Server_Satna" : 0,
    "ReloadCam_Server_Satunivers" : 5,
    "ReloadCam_Server_Seduct" : 0,
    "ReloadCam_Server_Testious" : 5,
    "ReloadCam_Server_Toopccam" : 0,
    "ReloadCam_Server_Ultrahd" : 0,
    "ReloadCam_Server_Xhaka" : 0,
    "ReloadCam_Server_Myfree" : 0,
    "ReloadCam_Server_Mawali" : 0,
    "ReloadCam_Server_Demed" : 0,
    "ReloadCam_Server_ManiaForall" : 0,
    "ReloadCam_Server_Foot4sport" : 0,
    "ReloadCam_Server_Top2servers" : 2,
    "ReloadCam_Server_Mario" : 0,
    "ReloadCam_Server_Madvengers" : 0,
    "ReloadCam_Server_Cccamgenerador" : 2,
    "ReloadCam_Server_Kingcccam" : 0,
    "ReloadCam_Server_Cccam4k" : 2,
    "ReloadCam_Server_Freecccam" : 1,
    "ReloadCam_Server_Freeccamserver" : 2,
    "ReloadCam_Server_Onecccam" : 0,
    "ReloadCam_Server_Bilalon" : 0,
    "ReloadCam_Server_Bosscccam" : 2,
    "ReloadCam_Server_Cccamlux" : 1,
    "ReloadCam_Server_Powerfull" : 1,
    "ReloadCam_Server_Cccamspot" : 1,
}

